import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import IndexOptionbar from "@/components/Optionsbar/Index.Optionbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Video Dubber AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        {children}
      </body>
    </html>
  );
}
